name: chai
description: "Chai Solutions app for SFSU CSC-648 capstone project"
publish_to: "none"

# The build number will be updated in CI based on the latest version
# from TestFlight and Google Play.
version: 0.1.0+1

environment:
  sdk: ^3.5.2
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  riverpod_annotation: ^2.3.5
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
flutter_native_splash:
  color: "#000000"
  image: "assets/images/app-icon.png"
  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    icon_background_color_dark: "#000000"
