default_platform(:ios)

platform :ios do
  lane :internal_testing do
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive"
    )
    upload_to_testflight
  end
end
